-- Curated affiliate picks (amzn.to links — May 2026 batch).
-- Run once in Supabase after 0010. Avoid re-running if rows already exist (no unique on external_url), or delete by external_url first.
-- Prices/images pulled from product pages at seed time — re-check on Amazon before relying on them.

insert into public.marketplace_catalog_items (
  title,
  description,
  price_cents,
  shipping_cents,
  currency,
  image_urls,
  purchase_mode,
  external_url,
  affiliate_note,
  active,
  sort_order
) values
(
  'HYMOKEGE — comforter 7 moso king, seersucker, sezon',
  'Set dora ak oreye, seersucker, tout sezon. Lyen Amazon — verifye mezè (king) ak pri.',
  3999,
  0,
  'usd',
  array['https://m.media-amazon.com/images/I/81VVMnTq4aL._AC_SL1500_.jpg']::text[],
  'external_affiliate',
  'https://amzn.to/4njs94v',
  'Lyen partenè Amazon. Zenlakay ka twen yon komisyon sou acha ki kalifye.',
  true,
  1020
),
(
  'Maillot sokè Ayiti personnalize — non ak nimewo (Zaanga)',
  'Maillot poliester 100%, koulè Haiti, personnalize. Lyen Amazon.',
  1999,
  0,
  'usd',
  array['https://m.media-amazon.com/images/I/71GuiRg6OUL._AC_SL1500_.jpg']::text[],
  'external_affiliate',
  'https://amzn.to/4301DUe',
  'Lyen partenè Amazon. Zenlakay ka twen yon komisyon sou acha ki kalifye.',
  true,
  1019
),
(
  '228CLOSET — maillot sokè Ayiti 2026, non ak nimewo',
  'Maillot fan sokè, personnalize. Lyen Amazon — verifye gwosè.',
  1399,
  0,
  'usd',
  array['https://m.media-amazon.com/images/I/7129fW-fWrL._AC_SL1254_.jpg']::text[],
  'external_affiliate',
  'https://amzn.to/4nmxZC4',
  'Lyen partenè Amazon. Zenlakay ka twen yon komisyon sou acha ki kalifye.',
  true,
  1018
),
(
  'Yasala — gobe isolé drapo Ayiti (tumbler)',
  'Gobe kafe / bwason, izolé, grafik Ayiti. Lyen Amazon.',
  2799,
  0,
  'usd',
  array['https://m.media-amazon.com/images/I/61mSc9Qf7NL._AC_SL1500_.jpg']::text[],
  'external_affiliate',
  'https://amzn.to/4uEnEnA',
  'Lyen partenè Amazon. Zenlakay ka twen yon komisyon sou acha ki kalifye.',
  true,
  1017
),
(
  'Trendessence — casquette baseball fan Ayiti Kup 2026',
  'Casquette reglab, tem fan mondyal. Lyen Amazon.',
  1999,
  0,
  'usd',
  array['https://m.media-amazon.com/images/I/8177IReO3kL._AC_SL1500_.jpg']::text[],
  'external_affiliate',
  'https://amzn.to/4fc8Eso',
  'Lyen partenè Amazon. Zenlakay ka twen yon komisyon sou acha ki kalifye.',
  true,
  1016
),
(
  'Bonnet slouchy drapo Ayiti — beanie mol',
  'Bonnet drapo Ayiti, mol, pou fanm / gason. Lyen Amazon.',
  999,
  0,
  'usd',
  array['https://m.media-amazon.com/images/I/71Op-ubo7PL._AC_SL1500_.jpg']::text[],
  'external_affiliate',
  'https://amzn.to/3R081bx',
  'Lyen partenè Amazon. Zenlakay ka twen yon komisyon sou acha ki kalifye.',
  true,
  1015
),
(
  'Onegam — jersey baseball Ayiti personnalize',
  'Jersey respiran, non nimewo personnalize. Lyen Amazon — verifye gwosè.',
  1899,
  0,
  'usd',
  array['https://m.media-amazon.com/images/I/71LVqUU5-dL._AC_SL1500_.jpg']::text[],
  'external_affiliate',
  'https://amzn.to/4daVucx',
  'Lyen partenè Amazon. Zenlakay ka twen yon komisyon sou acha ki kalifye.',
  true,
  1014
),
(
  'Casquette denim brodée drapo Ayiti — vintage',
  'Casquette baseball denim, brodri drapo, reglab. Lyen Amazon.',
  1999,
  0,
  'usd',
  array['https://m.media-amazon.com/images/I/719jmG8ZqoL._AC_SL1500_.jpg']::text[],
  'external_affiliate',
  'https://amzn.to/4uHQVOf',
  'Lyen partenè Amazon. Zenlakay ka twen yon komisyon sou acha ki kalifye.',
  true,
  1013
),
(
  'Chemiz fanm Ayiti — grafik eritaj, màn kout',
  'T-shirt eritaj Ayiti, grafik, màn kout. Lyen Amazon.',
  2699,
  0,
  'usd',
  array['https://m.media-amazon.com/images/I/71qVFmw63FL._AC_SL1500_.jpg']::text[],
  'external_affiliate',
  'https://amzn.to/4tWGzKc',
  'Lyen partenè Amazon. Zenlakay ka twen yon komisyon sou acha ki kalifye.',
  true,
  1012
),
(
  'Tank top été drapo Ayiti — fanm (crop / slim)',
  'Tank san màn, slim, tem drapo. Lyen Amazon — verifye gwosè.',
  2399,
  0,
  'usd',
  array['https://m.media-amazon.com/images/I/612uxamWgvL._AC_SL1500_.jpg']::text[],
  'external_affiliate',
  'https://amzn.to/4u0SMxo',
  'Lyen partenè Amazon. Zenlakay ka twen yon komisyon sou acha ki kalifye.',
  true,
  1011
),
(
  'Ti Malice — dispers vejetal, fèt ann Ayiti (1 lb)',
  'Ti Malice, pansman vejetal, produi soti Ayiti. Lyen Amazon.',
  899,
  0,
  'usd',
  array['https://m.media-amazon.com/images/I/61p8rqkC19L._SL1500_.jpg']::text[],
  'external_affiliate',
  'https://amzn.to/4d0oftJ',
  'Lyen partenè Amazon. Zenlakay ka twen yon komisyon sou acha ki kalifye.',
  true,
  1010
),
(
  'Djon Djon — 2 oz, grandi ann Ayiti (100% ayisyen)',
  'Djon djon sèk, spice ayisyen, 2 oz. Lyen Amazon.',
  1599,
  0,
  'usd',
  array['https://m.media-amazon.com/images/I/617uGldc9PL._SL1500_.jpg']::text[],
  'external_affiliate',
  'https://amzn.to/3QVh8u5',
  'Lyen partenè Amazon. Zenlakay ka twen yon komisyon sou acha ki kalifye.',
  true,
  1009
),
(
  'G2TUP — tabily kwizin ayisyen, kado kwit manje',
  'Apron kwizin tem Ayiti. Lyen Amazon.',
  1499,
  0,
  'usd',
  array['https://m.media-amazon.com/images/I/71x0mD5Bj4L._AC_SL1500_.jpg']::text[],
  'external_affiliate',
  'https://amzn.to/4nhTtzY',
  'Lyen partenè Amazon. Zenlakay ka twen yon komisyon sou acha ki kalifye.',
  true,
  1008
);
